spring:
  application:
    name: multagal
  profiles:
    default: dev

server:
  port: 8080

logging:
  level:
    es.edu.multagal: DEBUG

multagal:
  entrada:
    directorio: ./datos/entrada
  archivo:
    directorio: ./datos/archivo